// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/application/playlist"
	mock "github.com/stretchr/testify/mock"
)

// NewPlaylistService creates a new instance of PlaylistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistService {
	mock := &PlaylistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PlaylistService is an autogenerated mock type for the PlaylistService type
type PlaylistService struct {
	mock.Mock
}

type PlaylistService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistService) EXPECT() *PlaylistService_Expecter {
	return &PlaylistService_Expecter{mock: &_m.Mock}
}

// CreatePlaylist provides a mock function for the type PlaylistService
func (_mock *PlaylistService) CreatePlaylist(ctx context.Context, params playlist.CreatePlaylistParams) (playlist.CreatePlaylistResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlaylist")
	}

	var r0 playlist.CreatePlaylistResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, playlist.CreatePlaylistParams) (playlist.CreatePlaylistResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, playlist.CreatePlaylistParams) playlist.CreatePlaylistResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(playlist.CreatePlaylistResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, playlist.CreatePlaylistParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlaylistService_CreatePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlaylist'
type PlaylistService_CreatePlaylist_Call struct {
	*mock.Call
}

// CreatePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - params playlist.CreatePlaylistParams
func (_e *PlaylistService_Expecter) CreatePlaylist(ctx interface{}, params interface{}) *PlaylistService_CreatePlaylist_Call {
	return &PlaylistService_CreatePlaylist_Call{Call: _e.mock.On("CreatePlaylist", ctx, params)}
}

func (_c *PlaylistService_CreatePlaylist_Call) Run(run func(ctx context.Context, params playlist.CreatePlaylistParams)) *PlaylistService_CreatePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 playlist.CreatePlaylistParams
		if args[1] != nil {
			arg1 = args[1].(playlist.CreatePlaylistParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlaylistService_CreatePlaylist_Call) Return(createPlaylistResult playlist.CreatePlaylistResult, err error) *PlaylistService_CreatePlaylist_Call {
	_c.Call.Return(createPlaylistResult, err)
	return _c
}

func (_c *PlaylistService_CreatePlaylist_Call) RunAndReturn(run func(ctx context.Context, params playlist.CreatePlaylistParams) (playlist.CreatePlaylistResult, error)) *PlaylistService_CreatePlaylist_Call {
	_c.Call.Return(run)
	return _c
}
