// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthenticationFactory creates a new instance of AuthenticationFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationFactory {
	mock := &AuthenticationFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthenticationFactory is an autogenerated mock type for the AuthenticationFactory type
type AuthenticationFactory struct {
	mock.Mock
}

type AuthenticationFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticationFactory) EXPECT() *AuthenticationFactory_Expecter {
	return &AuthenticationFactory_Expecter{mock: &_m.Mock}
}

// CreateAuthenticator provides a mock function for the type AuthenticationFactory
func (_mock *AuthenticationFactory) CreateAuthenticator(ctx context.Context, config domain.SpotifyAuthConfig) (domain.SpotifyAuthenticator, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthenticator")
	}

	var r0 domain.SpotifyAuthenticator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SpotifyAuthConfig) (domain.SpotifyAuthenticator, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SpotifyAuthConfig) domain.SpotifyAuthenticator); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SpotifyAuthenticator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SpotifyAuthConfig) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthenticationFactory_CreateAuthenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthenticator'
type AuthenticationFactory_CreateAuthenticator_Call struct {
	*mock.Call
}

// CreateAuthenticator is a helper method to define mock.On call
//   - ctx context.Context
//   - config domain.SpotifyAuthConfig
func (_e *AuthenticationFactory_Expecter) CreateAuthenticator(ctx interface{}, config interface{}) *AuthenticationFactory_CreateAuthenticator_Call {
	return &AuthenticationFactory_CreateAuthenticator_Call{Call: _e.mock.On("CreateAuthenticator", ctx, config)}
}

func (_c *AuthenticationFactory_CreateAuthenticator_Call) Run(run func(ctx context.Context, config domain.SpotifyAuthConfig)) *AuthenticationFactory_CreateAuthenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SpotifyAuthConfig
		if args[1] != nil {
			arg1 = args[1].(domain.SpotifyAuthConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthenticationFactory_CreateAuthenticator_Call) Return(spotifyAuthenticator domain.SpotifyAuthenticator, err error) *AuthenticationFactory_CreateAuthenticator_Call {
	_c.Call.Return(spotifyAuthenticator, err)
	return _c
}

func (_c *AuthenticationFactory_CreateAuthenticator_Call) RunAndReturn(run func(ctx context.Context, config domain.SpotifyAuthConfig) (domain.SpotifyAuthenticator, error)) *AuthenticationFactory_CreateAuthenticator_Call {
	_c.Call.Return(run)
	return _c
}
