// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewPlaylistRepository creates a new instance of PlaylistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistRepository {
	mock := &PlaylistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PlaylistRepository is an autogenerated mock type for the PlaylistRepository type
type PlaylistRepository struct {
	mock.Mock
}

type PlaylistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistRepository) EXPECT() *PlaylistRepository_Expecter {
	return &PlaylistRepository_Expecter{mock: &_m.Mock}
}

// CreatePlaylist provides a mock function for the type PlaylistRepository
func (_mock *PlaylistRepository) CreatePlaylist(ctx context.Context, playlist domain.Playlist, opts ...domain.CreatePlaylistOption) (domain.CreatePlaylistResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, playlist, opts)
	} else {
		tmpRet = _mock.Called(ctx, playlist)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreatePlaylist")
	}

	var r0 domain.CreatePlaylistResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Playlist, ...domain.CreatePlaylistOption) (domain.CreatePlaylistResult, error)); ok {
		return returnFunc(ctx, playlist, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Playlist, ...domain.CreatePlaylistOption) domain.CreatePlaylistResult); ok {
		r0 = returnFunc(ctx, playlist, opts...)
	} else {
		r0 = ret.Get(0).(domain.CreatePlaylistResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Playlist, ...domain.CreatePlaylistOption) error); ok {
		r1 = returnFunc(ctx, playlist, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlaylistRepository_CreatePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlaylist'
type PlaylistRepository_CreatePlaylist_Call struct {
	*mock.Call
}

// CreatePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlist domain.Playlist
//   - opts ...domain.CreatePlaylistOption
func (_e *PlaylistRepository_Expecter) CreatePlaylist(ctx interface{}, playlist interface{}, opts ...interface{}) *PlaylistRepository_CreatePlaylist_Call {
	return &PlaylistRepository_CreatePlaylist_Call{Call: _e.mock.On("CreatePlaylist",
		append([]interface{}{ctx, playlist}, opts...)...)}
}

func (_c *PlaylistRepository_CreatePlaylist_Call) Run(run func(ctx context.Context, playlist domain.Playlist, opts ...domain.CreatePlaylistOption)) *PlaylistRepository_CreatePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Playlist
		if args[1] != nil {
			arg1 = args[1].(domain.Playlist)
		}
		var arg2 []domain.CreatePlaylistOption
		var variadicArgs []domain.CreatePlaylistOption
		if len(args) > 2 {
			variadicArgs = args[2].([]domain.CreatePlaylistOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *PlaylistRepository_CreatePlaylist_Call) Return(createPlaylistResult domain.CreatePlaylistResult, err error) *PlaylistRepository_CreatePlaylist_Call {
	_c.Call.Return(createPlaylistResult, err)
	return _c
}

func (_c *PlaylistRepository_CreatePlaylist_Call) RunAndReturn(run func(ctx context.Context, playlist domain.Playlist, opts ...domain.CreatePlaylistOption) (domain.CreatePlaylistResult, error)) *PlaylistRepository_CreatePlaylist_Call {
	_c.Call.Return(run)
	return _c
}
