// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSpotifyClientFactory creates a new instance of SpotifyClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotifyClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotifyClientFactory {
	mock := &SpotifyClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SpotifyClientFactory is an autogenerated mock type for the SpotifyClientFactory type
type SpotifyClientFactory struct {
	mock.Mock
}

type SpotifyClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotifyClientFactory) EXPECT() *SpotifyClientFactory_Expecter {
	return &SpotifyClientFactory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type SpotifyClientFactory
func (_mock *SpotifyClientFactory) NewClient(httpClient *http.Client) domain.SpotifyClient {
	ret := _mock.Called(httpClient)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 domain.SpotifyClient
	if returnFunc, ok := ret.Get(0).(func(*http.Client) domain.SpotifyClient); ok {
		r0 = returnFunc(httpClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SpotifyClient)
		}
	}
	return r0
}

// SpotifyClientFactory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type SpotifyClientFactory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - httpClient *http.Client
func (_e *SpotifyClientFactory_Expecter) NewClient(httpClient interface{}) *SpotifyClientFactory_NewClient_Call {
	return &SpotifyClientFactory_NewClient_Call{Call: _e.mock.On("NewClient", httpClient)}
}

func (_c *SpotifyClientFactory_NewClient_Call) Run(run func(httpClient *http.Client)) *SpotifyClientFactory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Client
		if args[0] != nil {
			arg0 = args[0].(*http.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SpotifyClientFactory_NewClient_Call) Return(spotifyClient domain.SpotifyClient) *SpotifyClientFactory_NewClient_Call {
	_c.Call.Return(spotifyClient)
	return _c
}

func (_c *SpotifyClientFactory_NewClient_Call) RunAndReturn(run func(httpClient *http.Client) domain.SpotifyClient) *SpotifyClientFactory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}
