// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSpotifyClient creates a new instance of SpotifyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotifyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotifyClient {
	mock := &SpotifyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SpotifyClient is an autogenerated mock type for the SpotifyClient type
type SpotifyClient struct {
	mock.Mock
}

type SpotifyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotifyClient) EXPECT() *SpotifyClient_Expecter {
	return &SpotifyClient_Expecter{mock: &_m.Mock}
}

// CreatePlaylist provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) CreatePlaylist(ctx context.Context, user string, playlist domain.SpotifyPlaylist) error {
	ret := _mock.Called(ctx, user, playlist)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.SpotifyPlaylist) error); ok {
		r0 = returnFunc(ctx, user, playlist)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SpotifyClient_CreatePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlaylist'
type SpotifyClient_CreatePlaylist_Call struct {
	*mock.Call
}

// CreatePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - playlist domain.SpotifyPlaylist
func (_e *SpotifyClient_Expecter) CreatePlaylist(ctx interface{}, user interface{}, playlist interface{}) *SpotifyClient_CreatePlaylist_Call {
	return &SpotifyClient_CreatePlaylist_Call{Call: _e.mock.On("CreatePlaylist", ctx, user, playlist)}
}

func (_c *SpotifyClient_CreatePlaylist_Call) Run(run func(ctx context.Context, user string, playlist domain.SpotifyPlaylist)) *SpotifyClient_CreatePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.SpotifyPlaylist
		if args[2] != nil {
			arg2 = args[2].(domain.SpotifyPlaylist)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SpotifyClient_CreatePlaylist_Call) Return(err error) *SpotifyClient_CreatePlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SpotifyClient_CreatePlaylist_Call) RunAndReturn(run func(ctx context.Context, user string, playlist domain.SpotifyPlaylist) error) *SpotifyClient_CreatePlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) CurrentUser(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyClient_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type SpotifyClient_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotifyClient_Expecter) CurrentUser(ctx interface{}) *SpotifyClient_CurrentUser_Call {
	return &SpotifyClient_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx)}
}

func (_c *SpotifyClient_CurrentUser_Call) Run(run func(ctx context.Context)) *SpotifyClient_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SpotifyClient_CurrentUser_Call) Return(s string, err error) *SpotifyClient_CurrentUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SpotifyClient_CurrentUser_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *SpotifyClient_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTrack provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) SearchTrack(ctx context.Context, artist string, title string) (domain.SpotifySearchResult, error) {
	ret := _mock.Called(ctx, artist, title)

	if len(ret) == 0 {
		panic("no return value specified for SearchTrack")
	}

	var r0 domain.SpotifySearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.SpotifySearchResult, error)); ok {
		return returnFunc(ctx, artist, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.SpotifySearchResult); ok {
		r0 = returnFunc(ctx, artist, title)
	} else {
		r0 = ret.Get(0).(domain.SpotifySearchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, artist, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyClient_SearchTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTrack'
type SpotifyClient_SearchTrack_Call struct {
	*mock.Call
}

// SearchTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - artist string
//   - title string
func (_e *SpotifyClient_Expecter) SearchTrack(ctx interface{}, artist interface{}, title interface{}) *SpotifyClient_SearchTrack_Call {
	return &SpotifyClient_SearchTrack_Call{Call: _e.mock.On("SearchTrack", ctx, artist, title)}
}

func (_c *SpotifyClient_SearchTrack_Call) Run(run func(ctx context.Context, artist string, title string)) *SpotifyClient_SearchTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SpotifyClient_SearchTrack_Call) Return(spotifySearchResult domain.SpotifySearchResult, err error) *SpotifyClient_SearchTrack_Call {
	_c.Call.Return(spotifySearchResult, err)
	return _c
}

func (_c *SpotifyClient_SearchTrack_Call) RunAndReturn(run func(ctx context.Context, artist string, title string) (domain.SpotifySearchResult, error)) *SpotifyClient_SearchTrack_Call {
	_c.Call.Return(run)
	return _c
}
