// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSpotifyAuthProvider creates a new instance of SpotifyAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotifyAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotifyAuthProvider {
	mock := &SpotifyAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SpotifyAuthProvider is an autogenerated mock type for the SpotifyAuthProvider type
type SpotifyAuthProvider struct {
	mock.Mock
}

type SpotifyAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotifyAuthProvider) EXPECT() *SpotifyAuthProvider_Expecter {
	return &SpotifyAuthProvider_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type SpotifyAuthProvider
func (_mock *SpotifyAuthProvider) Authenticate(ctx context.Context) (*domain.SpotifyToken, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.SpotifyToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.SpotifyToken, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.SpotifyToken); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SpotifyToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyAuthProvider_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type SpotifyAuthProvider_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotifyAuthProvider_Expecter) Authenticate(ctx interface{}) *SpotifyAuthProvider_Authenticate_Call {
	return &SpotifyAuthProvider_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx)}
}

func (_c *SpotifyAuthProvider_Authenticate_Call) Run(run func(ctx context.Context)) *SpotifyAuthProvider_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SpotifyAuthProvider_Authenticate_Call) Return(spotifyToken *domain.SpotifyToken, err error) *SpotifyAuthProvider_Authenticate_Call {
	_c.Call.Return(spotifyToken, err)
	return _c
}

func (_c *SpotifyAuthProvider_Authenticate_Call) RunAndReturn(run func(ctx context.Context) (*domain.SpotifyToken, error)) *SpotifyAuthProvider_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// ClientFromToken provides a mock function for the type SpotifyAuthProvider
func (_mock *SpotifyAuthProvider) ClientFromToken(ctx context.Context, token *domain.SpotifyToken) domain.SpotifyClient {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ClientFromToken")
	}

	var r0 domain.SpotifyClient
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SpotifyToken) domain.SpotifyClient); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SpotifyClient)
		}
	}
	return r0
}

// SpotifyAuthProvider_ClientFromToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientFromToken'
type SpotifyAuthProvider_ClientFromToken_Call struct {
	*mock.Call
}

// ClientFromToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.SpotifyToken
func (_e *SpotifyAuthProvider_Expecter) ClientFromToken(ctx interface{}, token interface{}) *SpotifyAuthProvider_ClientFromToken_Call {
	return &SpotifyAuthProvider_ClientFromToken_Call{Call: _e.mock.On("ClientFromToken", ctx, token)}
}

func (_c *SpotifyAuthProvider_ClientFromToken_Call) Run(run func(ctx context.Context, token *domain.SpotifyToken)) *SpotifyAuthProvider_ClientFromToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SpotifyToken
		if args[1] != nil {
			arg1 = args[1].(*domain.SpotifyToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SpotifyAuthProvider_ClientFromToken_Call) Return(spotifyClient domain.SpotifyClient) *SpotifyAuthProvider_ClientFromToken_Call {
	_c.Call.Return(spotifyClient)
	return _c
}

func (_c *SpotifyAuthProvider_ClientFromToken_Call) RunAndReturn(run func(ctx context.Context, token *domain.SpotifyToken) domain.SpotifyClient) *SpotifyAuthProvider_ClientFromToken_Call {
	_c.Call.Return(run)
	return _c
}
