// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenStore creates a new instance of TokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenStore {
	mock := &TokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenStore is an autogenerated mock type for the TokenStore type
type TokenStore struct {
	mock.Mock
}

type TokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenStore) EXPECT() *TokenStore_Expecter {
	return &TokenStore_Expecter{mock: &_m.Mock}
}

// DeleteToken provides a mock function for the type TokenStore
func (_mock *TokenStore) DeleteToken(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_DeleteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToken'
type TokenStore_DeleteToken_Call struct {
	*mock.Call
}

// DeleteToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenStore_Expecter) DeleteToken(ctx interface{}) *TokenStore_DeleteToken_Call {
	return &TokenStore_DeleteToken_Call{Call: _e.mock.On("DeleteToken", ctx)}
}

func (_c *TokenStore_DeleteToken_Call) Run(run func(ctx context.Context)) *TokenStore_DeleteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenStore_DeleteToken_Call) Return(err error) *TokenStore_DeleteToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_DeleteToken_Call) RunAndReturn(run func(ctx context.Context) error) *TokenStore_DeleteToken_Call {
	_c.Call.Return(run)
	return _c
}

// LoadToken provides a mock function for the type TokenStore
func (_mock *TokenStore) LoadToken(ctx context.Context) (*domain.SpotifyToken, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadToken")
	}

	var r0 *domain.SpotifyToken
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.SpotifyToken, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.SpotifyToken); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SpotifyToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenStore_LoadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadToken'
type TokenStore_LoadToken_Call struct {
	*mock.Call
}

// LoadToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenStore_Expecter) LoadToken(ctx interface{}) *TokenStore_LoadToken_Call {
	return &TokenStore_LoadToken_Call{Call: _e.mock.On("LoadToken", ctx)}
}

func (_c *TokenStore_LoadToken_Call) Run(run func(ctx context.Context)) *TokenStore_LoadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenStore_LoadToken_Call) Return(spotifyToken *domain.SpotifyToken, b bool, err error) *TokenStore_LoadToken_Call {
	_c.Call.Return(spotifyToken, b, err)
	return _c
}

func (_c *TokenStore_LoadToken_Call) RunAndReturn(run func(ctx context.Context) (*domain.SpotifyToken, bool, error)) *TokenStore_LoadToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type TokenStore
func (_mock *TokenStore) SaveToken(ctx context.Context, token *domain.SpotifyToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SpotifyToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type TokenStore_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.SpotifyToken
func (_e *TokenStore_Expecter) SaveToken(ctx interface{}, token interface{}) *TokenStore_SaveToken_Call {
	return &TokenStore_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, token)}
}

func (_c *TokenStore_SaveToken_Call) Run(run func(ctx context.Context, token *domain.SpotifyToken)) *TokenStore_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SpotifyToken
		if args[1] != nil {
			arg1 = args[1].(*domain.SpotifyToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenStore_SaveToken_Call) Return(err error) *TokenStore_SaveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_SaveToken_Call) RunAndReturn(run func(ctx context.Context, token *domain.SpotifyToken) error) *TokenStore_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}
