// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSetlistFMService creates a new instance of SetlistFMService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSetlistFMService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SetlistFMService {
	mock := &SetlistFMService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SetlistFMService is an autogenerated mock type for the SetlistFMService type
type SetlistFMService struct {
	mock.Mock
}

type SetlistFMService_Expecter struct {
	mock *mock.Mock
}

func (_m *SetlistFMService) EXPECT() *SetlistFMService_Expecter {
	return &SetlistFMService_Expecter{mock: &_m.Mock}
}

// GetSetlists provides a mock function for the type SetlistFMService
func (_mock *SetlistFMService) GetSetlists(ctx context.Context, artist string, opts ...domain.GetSetlistOption) ([]domain.Setlist, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, artist, opts)
	} else {
		tmpRet = _mock.Called(ctx, artist)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSetlists")
	}

	var r0 []domain.Setlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...domain.GetSetlistOption) ([]domain.Setlist, error)); ok {
		return returnFunc(ctx, artist, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...domain.GetSetlistOption) []domain.Setlist); ok {
		r0 = returnFunc(ctx, artist, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Setlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...domain.GetSetlistOption) error); ok {
		r1 = returnFunc(ctx, artist, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SetlistFMService_GetSetlists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetlists'
type SetlistFMService_GetSetlists_Call struct {
	*mock.Call
}

// GetSetlists is a helper method to define mock.On call
//   - ctx context.Context
//   - artist string
//   - opts ...domain.GetSetlistOption
func (_e *SetlistFMService_Expecter) GetSetlists(ctx interface{}, artist interface{}, opts ...interface{}) *SetlistFMService_GetSetlists_Call {
	return &SetlistFMService_GetSetlists_Call{Call: _e.mock.On("GetSetlists",
		append([]interface{}{ctx, artist}, opts...)...)}
}

func (_c *SetlistFMService_GetSetlists_Call) Run(run func(ctx context.Context, artist string, opts ...domain.GetSetlistOption)) *SetlistFMService_GetSetlists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []domain.GetSetlistOption
		var variadicArgs []domain.GetSetlistOption
		if len(args) > 2 {
			variadicArgs = args[2].([]domain.GetSetlistOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SetlistFMService_GetSetlists_Call) Return(setlists []domain.Setlist, err error) *SetlistFMService_GetSetlists_Call {
	_c.Call.Return(setlists, err)
	return _c
}

func (_c *SetlistFMService_GetSetlists_Call) RunAndReturn(run func(ctx context.Context, artist string, opts ...domain.GetSetlistOption) ([]domain.Setlist, error)) *SetlistFMService_GetSetlists_Call {
	_c.Call.Return(run)
	return _c
}
