// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/michaelheyman/spotify-setlist/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionService creates a new instance of SessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionService {
	mock := &SessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionService is an autogenerated mock type for the SessionService type
type SessionService struct {
	mock.Mock
}

type SessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionService) EXPECT() *SessionService_Expecter {
	return &SessionService_Expecter{mock: &_m.Mock}
}

// AuthenticatedClient provides a mock function for the type SessionService
func (_mock *SessionService) AuthenticatedClient(ctx context.Context) (domain.SpotifyClient, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticatedClient")
	}

	var r0 domain.SpotifyClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.SpotifyClient, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.SpotifyClient); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SpotifyClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionService_AuthenticatedClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticatedClient'
type SessionService_AuthenticatedClient_Call struct {
	*mock.Call
}

// AuthenticatedClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SessionService_Expecter) AuthenticatedClient(ctx interface{}) *SessionService_AuthenticatedClient_Call {
	return &SessionService_AuthenticatedClient_Call{Call: _e.mock.On("AuthenticatedClient", ctx)}
}

func (_c *SessionService_AuthenticatedClient_Call) Run(run func(ctx context.Context)) *SessionService_AuthenticatedClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionService_AuthenticatedClient_Call) Return(spotifyClient domain.SpotifyClient, err error) *SessionService_AuthenticatedClient_Call {
	_c.Call.Return(spotifyClient, err)
	return _c
}

func (_c *SessionService_AuthenticatedClient_Call) RunAndReturn(run func(ctx context.Context) (domain.SpotifyClient, error)) *SessionService_AuthenticatedClient_Call {
	_c.Call.Return(run)
	return _c
}
