// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewURLOpener creates a new instance of URLOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLOpener {
	mock := &URLOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// URLOpener is an autogenerated mock type for the URLOpener type
type URLOpener struct {
	mock.Mock
}

type URLOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *URLOpener) EXPECT() *URLOpener_Expecter {
	return &URLOpener_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type URLOpener
func (_mock *URLOpener) Open(url string) error {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// URLOpener_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type URLOpener_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - url string
func (_e *URLOpener_Expecter) Open(url interface{}) *URLOpener_Open_Call {
	return &URLOpener_Open_Call{Call: _e.mock.On("Open", url)}
}

func (_c *URLOpener_Open_Call) Run(run func(url string)) *URLOpener_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *URLOpener_Open_Call) Return(err error) *URLOpener_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *URLOpener_Open_Call) RunAndReturn(run func(url string) error) *URLOpener_Open_Call {
	_c.Call.Return(run)
	return _c
}
