// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zmb3/spotify/v2"
)

// NewSpotifyClient creates a new instance of SpotifyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotifyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotifyClient {
	mock := &SpotifyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SpotifyClient is an autogenerated mock type for the SpotifyClient type
type SpotifyClient struct {
	mock.Mock
}

type SpotifyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotifyClient) EXPECT() *SpotifyClient_Expecter {
	return &SpotifyClient_Expecter{mock: &_m.Mock}
}

// AddTracksToPlaylist provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) AddTracksToPlaylist(ctx context.Context, playlistID spotify.ID, trackIDs ...spotify.ID) (string, error) {
	var tmpRet mock.Arguments
	if len(trackIDs) > 0 {
		tmpRet = _mock.Called(ctx, playlistID, trackIDs)
	} else {
		tmpRet = _mock.Called(ctx, playlistID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddTracksToPlaylist")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spotify.ID, ...spotify.ID) (string, error)); ok {
		return returnFunc(ctx, playlistID, trackIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spotify.ID, ...spotify.ID) string); ok {
		r0 = returnFunc(ctx, playlistID, trackIDs...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spotify.ID, ...spotify.ID) error); ok {
		r1 = returnFunc(ctx, playlistID, trackIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyClient_AddTracksToPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTracksToPlaylist'
type SpotifyClient_AddTracksToPlaylist_Call struct {
	*mock.Call
}

// AddTracksToPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID spotify.ID
//   - trackIDs ...spotify.ID
func (_e *SpotifyClient_Expecter) AddTracksToPlaylist(ctx interface{}, playlistID interface{}, trackIDs ...interface{}) *SpotifyClient_AddTracksToPlaylist_Call {
	return &SpotifyClient_AddTracksToPlaylist_Call{Call: _e.mock.On("AddTracksToPlaylist",
		append([]interface{}{ctx, playlistID}, trackIDs...)...)}
}

func (_c *SpotifyClient_AddTracksToPlaylist_Call) Run(run func(ctx context.Context, playlistID spotify.ID, trackIDs ...spotify.ID)) *SpotifyClient_AddTracksToPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spotify.ID
		if args[1] != nil {
			arg1 = args[1].(spotify.ID)
		}
		var arg2 []spotify.ID
		var variadicArgs []spotify.ID
		if len(args) > 2 {
			variadicArgs = args[2].([]spotify.ID)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SpotifyClient_AddTracksToPlaylist_Call) Return(snapshotID string, err error) *SpotifyClient_AddTracksToPlaylist_Call {
	_c.Call.Return(snapshotID, err)
	return _c
}

func (_c *SpotifyClient_AddTracksToPlaylist_Call) RunAndReturn(run func(ctx context.Context, playlistID spotify.ID, trackIDs ...spotify.ID) (string, error)) *SpotifyClient_AddTracksToPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePlaylistForUser provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) CreatePlaylistForUser(ctx context.Context, userID string, playlistName string, description string, public bool, collaborative bool) (*spotify.FullPlaylist, error) {
	ret := _mock.Called(ctx, userID, playlistName, description, public, collaborative)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlaylistForUser")
	}

	var r0 *spotify.FullPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool, bool) (*spotify.FullPlaylist, error)); ok {
		return returnFunc(ctx, userID, playlistName, description, public, collaborative)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool, bool) *spotify.FullPlaylist); ok {
		r0 = returnFunc(ctx, userID, playlistName, description, public, collaborative)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spotify.FullPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, bool, bool) error); ok {
		r1 = returnFunc(ctx, userID, playlistName, description, public, collaborative)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyClient_CreatePlaylistForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlaylistForUser'
type SpotifyClient_CreatePlaylistForUser_Call struct {
	*mock.Call
}

// CreatePlaylistForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - playlistName string
//   - description string
//   - public bool
//   - collaborative bool
func (_e *SpotifyClient_Expecter) CreatePlaylistForUser(ctx interface{}, userID interface{}, playlistName interface{}, description interface{}, public interface{}, collaborative interface{}) *SpotifyClient_CreatePlaylistForUser_Call {
	return &SpotifyClient_CreatePlaylistForUser_Call{Call: _e.mock.On("CreatePlaylistForUser", ctx, userID, playlistName, description, public, collaborative)}
}

func (_c *SpotifyClient_CreatePlaylistForUser_Call) Run(run func(ctx context.Context, userID string, playlistName string, description string, public bool, collaborative bool)) *SpotifyClient_CreatePlaylistForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *SpotifyClient_CreatePlaylistForUser_Call) Return(fullPlaylist *spotify.FullPlaylist, err error) *SpotifyClient_CreatePlaylistForUser_Call {
	_c.Call.Return(fullPlaylist, err)
	return _c
}

func (_c *SpotifyClient_CreatePlaylistForUser_Call) RunAndReturn(run func(ctx context.Context, userID string, playlistName string, description string, public bool, collaborative bool) (*spotify.FullPlaylist, error)) *SpotifyClient_CreatePlaylistForUser_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) CurrentUser(ctx context.Context) (*spotify.PrivateUser, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 *spotify.PrivateUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*spotify.PrivateUser, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *spotify.PrivateUser); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spotify.PrivateUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyClient_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type SpotifyClient_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotifyClient_Expecter) CurrentUser(ctx interface{}) *SpotifyClient_CurrentUser_Call {
	return &SpotifyClient_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx)}
}

func (_c *SpotifyClient_CurrentUser_Call) Run(run func(ctx context.Context)) *SpotifyClient_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SpotifyClient_CurrentUser_Call) Return(privateUser *spotify.PrivateUser, err error) *SpotifyClient_CurrentUser_Call {
	_c.Call.Return(privateUser, err)
	return _c
}

func (_c *SpotifyClient_CurrentUser_Call) RunAndReturn(run func(ctx context.Context) (*spotify.PrivateUser, error)) *SpotifyClient_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type SpotifyClient
func (_mock *SpotifyClient) Search(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption) (*spotify.SearchResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, query, t, opts)
	} else {
		tmpRet = _mock.Called(ctx, query, t)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *spotify.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, spotify.SearchType, ...spotify.RequestOption) (*spotify.SearchResult, error)); ok {
		return returnFunc(ctx, query, t, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, spotify.SearchType, ...spotify.RequestOption) *spotify.SearchResult); ok {
		r0 = returnFunc(ctx, query, t, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spotify.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, spotify.SearchType, ...spotify.RequestOption) error); ok {
		r1 = returnFunc(ctx, query, t, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type SpotifyClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - t spotify.SearchType
//   - opts ...spotify.RequestOption
func (_e *SpotifyClient_Expecter) Search(ctx interface{}, query interface{}, t interface{}, opts ...interface{}) *SpotifyClient_Search_Call {
	return &SpotifyClient_Search_Call{Call: _e.mock.On("Search",
		append([]interface{}{ctx, query, t}, opts...)...)}
}

func (_c *SpotifyClient_Search_Call) Run(run func(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption)) *SpotifyClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 spotify.SearchType
		if args[2] != nil {
			arg2 = args[2].(spotify.SearchType)
		}
		var arg3 []spotify.RequestOption
		var variadicArgs []spotify.RequestOption
		if len(args) > 3 {
			variadicArgs = args[3].([]spotify.RequestOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *SpotifyClient_Search_Call) Return(searchResult *spotify.SearchResult, err error) *SpotifyClient_Search_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *SpotifyClient_Search_Call) RunAndReturn(run func(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption) (*spotify.SearchResult, error)) *SpotifyClient_Search_Call {
	_c.Call.Return(run)
	return _c
}
