// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewSpotifyAuthenticator creates a new instance of SpotifyAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotifyAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotifyAuthenticator {
	mock := &SpotifyAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SpotifyAuthenticator is an autogenerated mock type for the SpotifyAuthenticator type
type SpotifyAuthenticator struct {
	mock.Mock
}

type SpotifyAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotifyAuthenticator) EXPECT() *SpotifyAuthenticator_Expecter {
	return &SpotifyAuthenticator_Expecter{mock: &_m.Mock}
}

// AuthURL provides a mock function for the type SpotifyAuthenticator
func (_mock *SpotifyAuthenticator) AuthURL(state string, opts ...oauth2.AuthCodeOption) string {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(state, opts)
	} else {
		tmpRet = _mock.Called(state)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, ...oauth2.AuthCodeOption) string); ok {
		r0 = returnFunc(state, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SpotifyAuthenticator_AuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthURL'
type SpotifyAuthenticator_AuthURL_Call struct {
	*mock.Call
}

// AuthURL is a helper method to define mock.On call
//   - state string
//   - opts ...oauth2.AuthCodeOption
func (_e *SpotifyAuthenticator_Expecter) AuthURL(state interface{}, opts ...interface{}) *SpotifyAuthenticator_AuthURL_Call {
	return &SpotifyAuthenticator_AuthURL_Call{Call: _e.mock.On("AuthURL",
		append([]interface{}{state}, opts...)...)}
}

func (_c *SpotifyAuthenticator_AuthURL_Call) Run(run func(state string, opts ...oauth2.AuthCodeOption)) *SpotifyAuthenticator_AuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []oauth2.AuthCodeOption
		var variadicArgs []oauth2.AuthCodeOption
		if len(args) > 1 {
			variadicArgs = args[1].([]oauth2.AuthCodeOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SpotifyAuthenticator_AuthURL_Call) Return(s string) *SpotifyAuthenticator_AuthURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SpotifyAuthenticator_AuthURL_Call) RunAndReturn(run func(state string, opts ...oauth2.AuthCodeOption) string) *SpotifyAuthenticator_AuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// Client provides a mock function for the type SpotifyAuthenticator
func (_mock *SpotifyAuthenticator) Client(ctx context.Context, token *oauth2.Token) *http.Client {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 *http.Client
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth2.Token) *http.Client); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	return r0
}

// SpotifyAuthenticator_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type SpotifyAuthenticator_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
//   - ctx context.Context
//   - token *oauth2.Token
func (_e *SpotifyAuthenticator_Expecter) Client(ctx interface{}, token interface{}) *SpotifyAuthenticator_Client_Call {
	return &SpotifyAuthenticator_Client_Call{Call: _e.mock.On("Client", ctx, token)}
}

func (_c *SpotifyAuthenticator_Client_Call) Run(run func(ctx context.Context, token *oauth2.Token)) *SpotifyAuthenticator_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *oauth2.Token
		if args[1] != nil {
			arg1 = args[1].(*oauth2.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SpotifyAuthenticator_Client_Call) Return(client *http.Client) *SpotifyAuthenticator_Client_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *SpotifyAuthenticator_Client_Call) RunAndReturn(run func(ctx context.Context, token *oauth2.Token) *http.Client) *SpotifyAuthenticator_Client_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function for the type SpotifyAuthenticator
func (_mock *SpotifyAuthenticator) Token(ctx context.Context, state string, r *http.Request, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, state, r, opts)
	} else {
		tmpRet = _mock.Called(ctx, state, r)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request, ...oauth2.AuthCodeOption) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, state, r, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request, ...oauth2.AuthCodeOption) *oauth2.Token); ok {
		r0 = returnFunc(ctx, state, r, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *http.Request, ...oauth2.AuthCodeOption) error); ok {
		r1 = returnFunc(ctx, state, r, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpotifyAuthenticator_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type SpotifyAuthenticator_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - r *http.Request
//   - opts ...oauth2.AuthCodeOption
func (_e *SpotifyAuthenticator_Expecter) Token(ctx interface{}, state interface{}, r interface{}, opts ...interface{}) *SpotifyAuthenticator_Token_Call {
	return &SpotifyAuthenticator_Token_Call{Call: _e.mock.On("Token",
		append([]interface{}{ctx, state, r}, opts...)...)}
}

func (_c *SpotifyAuthenticator_Token_Call) Run(run func(ctx context.Context, state string, r *http.Request, opts ...oauth2.AuthCodeOption)) *SpotifyAuthenticator_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *http.Request
		if args[2] != nil {
			arg2 = args[2].(*http.Request)
		}
		var arg3 []oauth2.AuthCodeOption
		var variadicArgs []oauth2.AuthCodeOption
		if len(args) > 3 {
			variadicArgs = args[3].([]oauth2.AuthCodeOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *SpotifyAuthenticator_Token_Call) Return(token *oauth2.Token, err error) *SpotifyAuthenticator_Token_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *SpotifyAuthenticator_Token_Call) RunAndReturn(run func(ctx context.Context, state string, r *http.Request, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error)) *SpotifyAuthenticator_Token_Call {
	_c.Call.Return(run)
	return _c
}
